### PR TITLE
Play icon added.

### PR DESCRIPTION
**Pull request by roland-vachter**
Play icon is used for brightcove video placeholders. It will be used in n-video, which might become o-video.

### CODE REVIEW

**Comment by onishiweb** [comment]
Looks good to me, but @AlbertoElias is working on icons at the moment so will let you check over it as well before merging.

**Comment by roland-vachter** [comment]
Demo data updated as well.

**Comment by AlbertoElias** [comment]
This looks great, thanks a lot @roland-vachter

**Comment by roland-vachter** [comment]
It seems that the demos are not working in the registry:
http://registry.origami.ft.com/components/o-ft-icons@3.5.0?cb=1461327439

Is that because of the registry?

**Pull request merged**
