### PR TITLE
Prototype icons

### PR DESCRIPTION
**Pull request by wheresrhys**
Originally used on swi.ft.com, but will probably be used for next

### CODE REVIEW

**Comment by kaelig** [comment]
Would you like to fix the merge conflicts? Or is this branch just for next?

**Comment by wheresrhys** [comment]
In next we're still not enabling o-ft-icons due to occasional emoji bugs on iphone, so for the moment we're just consuming these directly as svg... so no pressing need to merge. 

If and when we need to I'm happy to do all the conflict resolution

**Comment by kaelig** [comment]
If you're consuming these as SVG you might want to optimise them. Ideally we would have the same optimisation system as ft-icons (available on Stash)

**Comment by kaelig** [comment]
Closing this after 3 months of inactivity.

**Pull request closed without merging**
