### PR TITLE
Add new next icons

### PR DESCRIPTION
**Pull request by alicebartlett**
This PR:

- updates five icons: social-facebook, social-twitter, social-linkedin, print, and comment.
- adds new icon: copy-link
- normalises all icon colours to black. As we're going to deprecate our icon font in favour of an svg solution, the colour of the svgs should all be the same (before they were normalised to black by the icon-font-ifying process)

Visual diff for new/old icons:

Before | After
------------ | -------------
screen shot 2016-03-21 at 12 01 20 | screen shot 2016-03-21 at 12 00 18
screen shot 2016-03-21 at 12 01 31 |  screen shot 2016-03-21 at 12 00 27
screen shot 2016-03-21 at 12 01 26 |  screen shot 2016-03-21 at 12 00 23
screen shot 2016-03-21 at 12 01 06 | screen shot 2016-03-21 at 12 00 41
 | screen shot 2016-03-21 at 12 00 38
 | screen shot 2016-04-07 at 10 34 04
 | screen shot 2016-04-07 at 10 34 17
 | screen shot 2016-04-07 at 10 35 32
 | screen shot 2016-04-07 at 10 34 37
 | screen shot 2016-04-07 at 10 34 45
 | screen shot 2016-04-07 at 10 34 51

### CODE REVIEW

**Comment by onishiweb** [comment]
:+1:

**Comment by alicebartlett** [comment]
OK, waiting for this to be resolved: #126

**Comment by AlbertoElias** [comment]
@alicebartlett @SarahHornsey  How's this?

**Comment by alicebartlett** [comment]
Could you update the pr with the new icons you've added? that would make it easier for @SarahHornsey  to review too. 
You've accidentally committed the generated HTML for the demos too.
Otherwise this looks good. Thank you for picking it up.

**Comment by AlbertoElias** [comment]
@alicebartlett all done!

**Pull request merged**
