### PR TITLE
Create tick-green.svg

### PR DESCRIPTION
**Pull request by kaelig**
Since the image service doesn't support coloring yet, I'm creating this green variant.

If someone thinks it's a bad idea I can also directly embed the icon in the o-ft-forms assets.

### CODE REVIEW

**Comment by AlbertoElias** [comment]
The current icon is a font, can't you just use font-color?

**Comment by jamesnicholls** [comment]
@AlbertoElias Forms doesn't use the icon font, it uses the SVGs directly.

**Comment by AlbertoElias** [comment]
@jamesnicholls Yes, sorry, I spoke with Kaelig about it and we decided to go with an inline svg for now until the Image Service supports tinting

**Comment by kaelig** [comment]
Closing this as we're inlining the SVG in base64.

**Pull request closed without merging**
